title:            Min Guo
description:      Min blog
url:              http://min-guo.com
signoff:          Min Guo
disqus_shortname: Minsblog
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         About
    url:          /about
  - name:         Email
    url:          mailto:min@min-guo.com
    external:     true
  - name:         GitHub
    url:          https://github.com/Min-Guo
    external:     true
pygments:         true
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
